/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EventEditorFormWrapper.java
 *
 * Created on 13-Mar-2010, 6:20:56 PM
 */

package ca.uhn.hunit.swing.ui.event;

import ca.uhn.hunit.event.EventFactory;
import ca.uhn.hunit.ex.ConfigurationException;
import ca.uhn.hunit.l10n.Strings;
import ca.uhn.hunit.swing.controller.ctx.EventEditorContextController;
import ca.uhn.hunit.swing.ui.AbstractContextForm;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.TitledBorder;

/**
 *
 * @author James
 */
public class EventEditorFormWrapper extends AbstractContextForm<EventEditorContextController> {
    private AbstractEventEditorForm myNestedView;

    /** Creates new form EventEditorFormWrapper */
    public EventEditorFormWrapper() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myEventSummaryPanel = new javax.swing.JPanel();
        myEventDescriptionLabel = new javax.swing.JLabel();
        myEventEditorPanel = new javax.swing.JPanel();

        myEventSummaryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        myEventDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myEventDescriptionLabel.setText("jLabel1");

        javax.swing.GroupLayout myEventSummaryPanelLayout = new javax.swing.GroupLayout(myEventSummaryPanel);
        myEventSummaryPanel.setLayout(myEventSummaryPanelLayout);
        myEventSummaryPanelLayout.setHorizontalGroup(
            myEventSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myEventDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        myEventSummaryPanelLayout.setVerticalGroup(
            myEventSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myEventDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ca/uhn/hunit/l10n/UiStrings"); // NOI18N
        myEventEditorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("eventeditor.bordertitle"))); // NOI18N
        myEventEditorPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myEventSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myEventEditorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myEventSummaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myEventEditorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel myEventDescriptionLabel;
    private javax.swing.JPanel myEventEditorPanel;
    private javax.swing.JPanel myEventSummaryPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setController(EventEditorContextController theController) throws ConfigurationException {
        myNestedView = EventFactory.INSTANCE.createEditorForm(theController, theController.getEvent());

        myEventEditorPanel.removeAll();
        myEventEditorPanel.add(myNestedView, BorderLayout.CENTER);

        TitledBorder border = (TitledBorder) myEventSummaryPanel.getBorder();
        border.setTitle(Strings.getMessage(theController.getEvent().getResourceBundleSummaryKey()));

        myEventDescriptionLabel.setText(Strings.getMessage(theController.getEvent().getResourceBundleDescriptionKey()));
    }

    @Override
    public void tearDown() {
        myNestedView.tearDown();
    }

}
