/**
 *
 * The contents of this file are subject to the Mozilla Public License Version 1.1
 * (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.mozilla.org/MPL/
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the
 * specific language governing rights and limitations under the License.
 *
 * The Initial Developer of the Original Code is University Health Network. Copyright (C)
 * 2001.  All Rights Reserved.
 *
 * Alternatively, the contents of this file may be used under the terms of the
 * GNU General Public License (the  "GPL"), in which case the provisions of the GPL are
 * applicable instead of those above.  If you wish to allow use of your version of this
 * file only under the terms of the GPL and not to allow others to use your version
 * of this file under the MPL, indicate your decision by deleting  the provisions above
 * and replace  them with the notice and other provisions required by the GPL License.
 * If you do not delete the provisions above, a recipient may use your version of
 * this file under either the MPL or the GPL.
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Hl7V2ExpectSpecificMessageEditorForm.java
 *
 * Created on 17-Oct-2009, 2:27:34 PM
 */

package ca.uhn.hunit.swing.ui.event.expect;

import ca.uhn.hunit.event.expect.Hl7V2ExpectSpecificMessageImpl;
import ca.uhn.hunit.test.TestBatteryImpl;

/**
 *
 * @author James
 */
public class Hl7V2ExpectSpecificMessageEditorForm extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
    
    private final TestBatteryImpl myBattery;
    private final Hl7V2ExpectSpecificMessageImpl myEvent;

    /** Creates new form Hl7V2ExpectSpecificMessageEditorForm */
    public Hl7V2ExpectSpecificMessageEditorForm() {
        myBattery = new TestBatteryImpl();
        myEvent = null;

        initComponents();
    }

    /** Creates new form Hl7V2ExpectSpecificMessageEditorForm */
    public Hl7V2ExpectSpecificMessageEditorForm(TestBatteryImpl theBattery, Hl7V2ExpectSpecificMessageImpl theEvent) {
        myBattery = theBattery;
        myEvent = theEvent;

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseEventEditorForm1 = new ca.uhn.hunit.swing.ui.event.expect.BaseEventEditorForm();
        myEventEditorForm = new BaseEventEditorForm(myBattery, myEvent);
        mySpecificMessageEditorForm = new BaseSpecificMessageEditorForm(myBattery, myEvent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myEventEditorForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mySpecificMessageEditorForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myEventEditorForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mySpecificMessageEditorForm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ca.uhn.hunit.swing.ui.event.expect.BaseEventEditorForm baseEventEditorForm1;
    private ca.uhn.hunit.swing.ui.event.expect.BaseEventEditorForm myEventEditorForm;
    private ca.uhn.hunit.swing.ui.event.expect.BaseSpecificMessageEditorForm mySpecificMessageEditorForm;
    // End of variables declaration//GEN-END:variables

}
