/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfaceForm.java
 *
 * Created on 4-Oct-2009, 5:22:57 PM
 */

package ca.uhn.hunit.swing.ui;

import ca.uhn.hunit.iface.AbstractInterface;
import ca.uhn.hunit.swing.controller.ctx.AbstractInterfaceEditorContextController;
import javax.swing.JPanel;

/**
 *
 * @author James
 */
public class InterfaceForm extends javax.swing.JPanel {

    private final AbstractInterfaceEditorContextController<?, ?> myController;

    /** Creates new form InterfaceForm */
    public InterfaceForm() {
        initComponents();
        this.myController = null;
    }

    /** Creates new form InterfaceForm */
    public <T extends AbstractInterface, V extends JPanel> InterfaceForm(AbstractInterfaceEditorContextController<T, V> theController) {
        initComponents();
        this.myController = theController;

        setValues();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        myIdTextBox = new javax.swing.JTextField();
        myAutostartCheckBox = new javax.swing.JCheckBox();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setLabelFor(myIdTextBox);
        jLabel1.setText("ID");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setLabelFor(myAutostartCheckBox);
        jLabel2.setText("Autostart");

        myIdTextBox.setText("jTextField1");

        myAutostartCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAutostartCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myIdTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myAutostartCheckBox))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myIdTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(myAutostartCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myAutostartCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAutostartCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myAutostartCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox myAutostartCheckBox;
    private javax.swing.JTextField myIdTextBox;
    // End of variables declaration//GEN-END:variables

    public void setValues() {
        if (myController != null) {
            myAutostartCheckBox.setSelected(myController.getModel().isAutostart());
            myIdTextBox.setText(myController.getModel().getId());
        }
    }

}
